name: Main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Use Node.js
        uses: action/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm Install
